### ISSUE TITLE
How to register children to schools

### ISSUE THREAD

**Issue by dhirajgraycelltech** [idega/com.idega.block.school#1]
Hi,

I've created new schools in idega, now i want to do this.
That is given in Municipality processes.

Primary school applications – School selection process
Registering children for the first grade takes place online. 

But, 
![p1](https://user-images.githubusercontent.com/38747709/39865070-6221971a-5469-11e8-8a9d-3b92a5e70776.png)
I don't know which modules may or may not be used to do this. I just want to create this things.. i have taken the full clone of eGov from BRANCH_PLATFORM_5.

And, i have noticed that when first time the lucid pom.xml contains this dependency regarding addon.

    <dependency>
      <groupId>com.idega.block.addon</groupId>
      <artifactId>com.idega.block.elight</artifactId>
    </dependency>
    <dependency>
      <groupId>com.idega.block.addon</groupId>
      <artifactId>com.idega.block.websearch</artifactId>
    </dependency>

After that, the idega showing me only few menu tabs on the top, why it is so?
And for eGov i have to give dependency entries by my own. there is so many times when i don't it is session or what, it is auto logout, & i have to login again for the same. 
Please describe little bit.

Attaching snapshot -
![p2](https://user-images.githubusercontent.com/38747709/39865071-6265e37a-5469-11e8-8f35-1b848654ef8b.png)

**Comment by dhirajgraycelltech** [comment]
Hello, 

The Idega,

Did not get the solution yet.. Please give at least some hint. I want to integrate one module completely.

Thanks... :-)

**Comment by valdaszem** [comment]
Hello,

Thanks for your interest in our ePlatform.

The functions you need are not in open source package - their are in private package. In case you would like to get access, please contact our CEO: Gunnar Páll Þórisson (gunnar@idega.com <mailto:gunnar@idega.com> or by mobile phone: +354 842 5775).

Regards,
Valdas

**Comment by dhirajgraycelltech** [comment]
Hi, 

Yeah, thanks too. We are so excited to work with Idega, such a big platform.

Oh, thank you so much. Actually,  i work very hard to finding these things but in the last i got the solution from you end. Because i was thinking may be i am wrong while setup all these things.
Okay i got the solution & we will contact Idega shortly.

Thank you so much. Cheers!!
